version: "3.8"
services:
  meeting_room:
    build: .
    volumes:
      - ./meeting_room:/meeting_room
    ports:
      - 8000:8000
    image: meeting_room:meeting_room
    container_name: meeting_room_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/db_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postPass
    container_name: db_postgre5
